apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmp-engine
  namespace: gameoflife
spec:
  replicas: 2  # Iniciar com 2 engines
  selector:
    matchLabels:
      app: openmp-engine
  template:
    metadata:
      labels:
        app: openmp-engine
    spec:
      containers:
      - name: openmp-engine
        image: gameoflife/openmp-engine:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 2000m
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: openmp-engine
  namespace: gameoflife
spec:
  selector:
    app: openmp-engine
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
---
# HPA para autoscaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: openmp-engine-hpa
  namespace: gameoflife
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openmp-engine
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
