apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-engine
  namespace: gameoflife
spec:
  replicas: 1 # O paralelismo é controlado pelos threads do spark-submit
  selector:
    matchLabels:
      app: spark-engine
  template:
    metadata:
      labels:
        app: spark-engine
    spec:
      containers:
      - name: spark-engine
        image: gameoflife/spark-engine:latest 
        imagePullPolicy: Never 
        command: ["/bin/bash", "-c", "tail -f /dev/null"] 
        resources:
          requests:
            memory: "2Gi" 
            cpu: "1000m" 
          limits:
            memory: "4Gi"
            cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-engine
  namespace: gameoflife
spec:
  selector:
    app: spark-engine
  ports:
  - port: 8082 
    targetPort: 8082
  type: ClusterIP