apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: gameoflife
spec:
  ports:
  - port: 7077
    targetPort: 7077
    name: cluster-port
  - port: 8080
    targetPort: 8080
    name: webui-port
  selector:
    app: spark-master
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: gameoflife
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:3.5
        imagePullPolicy: IfNotPresent
        env:
        - name: SPARK_MODE
          value: master
        - name: SPARK_MASTER_HOST
          value: "0.0.0.0"
        - name: SPARK_MASTER_PORT
          value: "7077"
        ports:
        - containerPort: 8080
        - containerPort: 7077
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"